import type { Metadata } from "next";
import "./globals.css";
import { Footer, Navbar } from "./components";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Toaster />

        {children}
        <Footer />
      </body>
    </html>
  );
}
